### ISSUE TITLE
Add apcu, intl, opcache to common extensions

### ISSUE THREAD

**Issue by henderkes** [static-php/static-php-cli-docs#3]
I think *every* project uses these. 

xslt and xls are also good contenders for this. And maybe pgsql/pdo_pgsql,  I don't know how often they are used since mysql is the default choice.

**Comment by crazywhalecc** [comment]
I know that internationalization projects may use it, but modifying common doesn't seem to make much sense.

`common` is more like a demo than a real common. Just as there are more than fifty extensions, I cannot publish all common combinations at the same time, such as someone needing a swoole to use octane and someone not needing it; Some people want the common to include imagick and all gd optional libraries because they are common drawing libraries, but they are still too large. The same applies to intl/icu, as once these seemingly commonly used libraries are included by default, the size will become larger. At the same time, because the common version has a historical version of PHP, I cannot keep changing the compilation results of the common.

BTW, I can also compile a `full` version of PHP that includes as many extensions as possible. But this also leads to a problem where certain extensions conflict with each other, and how to choose between them is another challenge.

**Comment by crazywhalecc** [comment]
I know that internationalization projects may use it, but modifying common doesn't seem to make much sense.

**For hosted common php-cli distributable:**

common is more like a demo than a real common. Just as there are more than 55+ extensions, I cannot publish all common combinations at the same time, such as someone needing a swoole to use octane and someone not needing it; Some people want the common to include imagick and all gd optional libraries because they are common drawing libraries, but they are still too large. The same applies to intl/icu, as once these seemingly commonly used libraries are included by default, the size will become larger. At the same time, because the common version has a historical version of PHP, I cannot keep changing the compilation results of the common.

**For documentation:**

The commands of the docs command generator are actually randomly selected by me. If you want them to be included, I will modify them the next time I write the docs.

BTW, I can also compile a full version of PHP that includes as many extensions as possible. But this also leads to a problem where certain extensions conflict with each other, and how to choose between them is another challenge.

**Comment by henderkes** [comment]
> The commands of the docs command generator are actually randomly selected by me. If you want them to be included, I will modify them the next time I write the docs.

I specifically thought about the "common" selector [here](https://static-php.dev/en/guide/cli-generator.html)

And I would think of "common" extensions as those that nearly every project uses, like mbstring, fileinfo, filter, ...
Gd maybe not as much, but intl is used in just about every project I can imagine, just like opcache is in the official recommendations. Apcu is very commonly used as a caching system backend of frameworks like Symfony/Laravel too.
